name: build

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: get-iplayer-version
        run: |
          echo $(cat version.txt)
          echo "::set-output name=version::$(cat version.txt)"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            xorima/get-iplayer:${{ steps.get-iplayer-version.output.version }}
            xorima/get-iplayer:${{ steps.get-iplayer-version.output.version }}-${GITHUB_SHA::8}
            xorima/get-iplayer:${{ steps.get-iplayer-version.output.version }}-${GITHUB_SHA::8}-${{ steps.build-date.output.build_date}}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            BUILD_DATE=${{ steps.build-date.output.build_date}}
            VCS_REF=${GITHUB_SHA::8}
            GET_IPLAYER_VERSION=${{ steps.get-iplayer-version.output.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
