name: build-latest

on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 0 * * *"
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build-date
        run: echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        id: build-date
      - name: Get Iplayer Version
        run: echo "::set-output name=version::*"
        id: version
      - name: Short git sha
        run: echo "::set-output name=short::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: git-sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            xorima/get-iplayer:latest
            xorima/get-iplayer:latest-${{ steps.git-sha.outputs.short }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            BUILD_DATE=${{ steps.build-date.outputs.build_date}}
            VCS_REF=${{ steps.git-sha.outputs.short }}
            GET_IPLAYER_VERSION=${{ steps.version.outputs.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
